version: '3.0'
services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - '$PWD/nginx/:/etc/nginx/conf.d/'
      - '$PWD/../:/usr/share/nginx/html/'
    networks:
      - lottery_net
    container_name: 'lottery-nginx'
  php:
    build: ./php
    image: php:7.1-fpm
    ports:
      - '9000:9000'
    volumes:
      - '$PWD/../:/usr/share/nginx/html/'
    networks:
      - lottery_net
    container_name: 'lottery-php'
  mysql:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      lottery_net:
        ipv4_address: 10.10.10.1
    container_name: 'lottery-mysql'
  redis:
    image: redis:4.0
    networks:
      - lottery_net
    container_name: 'lottery-redis'
networks:
  lottery_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
