version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - '$PWD/nginx/:/etc/nginx/conf.d/'
      - '$PWD/www:/usr/share/nginx/html'
    networks:
      - app_net
    container_name: 'lottery-nginx'
  php:
    build: ./php
    image: php:7.1-fpm
    ports:
      - '9001:9000'
    volumes:
      - '$PWD/www:/var/www/html'
    networks:
      - app_net
    container_name: 'lottery-php'
  mysql:
    image: mysql:5.6
    ports:
      - '33066:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      app_net:
        ipv4_address: 10.10.10.1
    container_name: 'lottery-mysql'
  redis:
    image: redis:4.0
    networks:
      - app_net
    container_name: 'lottery-redis'
networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
