<?php defined('BASEPATH') || exit('No direct script access allowed');

$config['use_page_numbers'] = true;
$config['uri_segment']      = 0;
$config['num_links']        = 4;
$config['first_link']       = '&laquo; 首页';
$config['last_link']        = '末页 &raquo;';
$config['prev_link']        = '&lsaquo; 上一页';
$config['next_link']        = '下一页 &rsaquo;';
$config['full_tag_open']    = '<ul class="pagination pagination-sm no-margin pull-right">';
$config['full_tag_close']   = '</ul>';
$config['first_tag_open']   = '<li>';
$config['first_tag_close']  = '</li>';
$config['last_tag_open']    = '<li>';
$config['last_tag_close']   = '</li>';
$config['prev_tag_open']    = '<li>';
$config['prev_tag_close']   = '</li>';
$config['next_tag_open']    = '<li>';
$config['next_tag_close']   = '</li>';
$config['num_tag_open']     = '<li>';
$config['num_tag_close']    = '</li>';
$config['cur_tag_open']     = '<li class="active"><a>';
$config['cur_tag_close']    = '</a></li>';
